name: Daily Data Pipeline

on:
  schedule:
    # Runs every day at 21:30 UTC = 4:30 PM EST
    - cron: '30 21 * * *'
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows committing changes back to repo

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance scipy numpy

      # Step 4: Run the Yahoo Finance scraper
      - name: Run scraper
        run: python scraper.py

      # Step 5: Append new data to existing CSVs
      # (Assuming scraper.py handles the appending logic internally)

      # Step 6: Run the converter to create .mat files
      - name: Convert CSVs to .mat
        run: python converter.py

      # Step 7: Create JSON file from .mat
      - name: Generate JSON file
        run: python json_creator.py

      # Step 8: Commit and push updated files
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated data update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
